### ISSUE TITLE
Difference of iteration count in camera-ready branch and main branch

### ISSUE THREAD

**Issue by Xinyu-Li-123** [netsharecmu/NetShare#10]
Hi, I have one problem about the configuration. I notice that the camera-ready branch has set the default iteration to 40 for pcap w/o dp while the main branch set it to 80000. Could you please explain this difference? Are the results in the NetShare essay produced by experiments using the config in camera-ready branch?

**Comment by sniperyyc** [comment]
Thank you for reaching out.

> I notice that the camera-ready branch has set the default iteration to 40 for pcap w/o dp while the main branch set it to 80000. Could you please explain this difference?

As written in the README, 

> We provide four different examples to cover the different datasets/scenarios that we described in the paper, i.e., PCAP (CAIDA dataset, with or without differential privacy), NetFlow (UGR16 dataset, with or without differential privacy). These examples use the exact same dataset as in the paper (1 million packets or flow records) but with a much smaller training iterations for quick validation. Therefore, the quality of the results generated by these example configurations (configs/config_test{i}) are not informative.
If you would like to reproduce the results in our paper, please use the configuration files named configs/config{i} and we recommend to follow the multi-machine setup guideline to achieve the maximum efficiency.

iteration=40 is just for quick E2E validation and does not generate informative results. 

> Are the results in the NetShare essay produced by experiments using the config in camera-ready branch?

You may refer to the configuration [here](https://github.com/netsharecmu/NetShare/blob/e73c1f9be1b45a5467fcf2a916d409c788da1a1c/src/configs/paper/config1_no_dp.py) but notice that it may not be plugged-in ready and up-to-date as we modified the codebase a lot since then.
You may also refer to the [branch from Purdue University](https://github.com/annuszulfiqar2021/NetShare) for a nice reproduction example and even added their own datasets!

We apologize for the possible confusion here and **recently did another refactor (python 3.9 and using PyTorch)**. We will release that version soon and please stay tuned. Thank you again for your interest in our work.
