### ISSUE TITLE
Bug when loading from chunk0 checkpoint

### ISSUE THREAD

**Issue by Xinyu-Li-123** [netsharecmu/NetShare#31]
When loading from chunk 0 checkpoint by setting `skip_chunk0_train` to `true`, the function [`_configs2configsgroup`](https://github.com/netsharecmu/NetShare/blob/f004f23a57d04e59a2c5b1a11211af6ac429ab28/netshare/model_managers/netshare_manager/netshare_util.py#L80) in `netshare/model_managers/netshare_manager/netshare_util.py` can't find the checkpoint correctly. I believe this is due to a bug in this function where the for loop for finding the latest checkpoint use an incorrect format of checkpoint file. 

The currrent format is
```python
ckpt_dir = os.path.join(
    configs[config_id]["result_folder"],
    "checkpoint",
    "epoch_id-{}".format(epoch_id)
)
```
whereas the correct format should be 
```python
ckpt_dir = os.path.join(
    configs[config_id]["result_folder"],
    "checkpoint",
    "epoch_id-{}.pt".format(epoch_id)
)
```

**Comment by sniperyyc** [comment]
Thanks, pushed the [fix](https://github.com/netsharecmu/NetShare/commit/cec0f3a0658fc7e7fe0a3179948fd5881122f4b8).

We have not really used this feature (i.e., `skip_chunk0_train`) for a while since it was designed for internal test/debug. Note that we are actively building and testing this PyTorch version so please stay tuned for more updates in the coming weeks.
